# Node.js with Angular

# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
steps:

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(system.defaultworkingdirectory)'
    Contents: '/'
    TargetFolder: '$(build.artifactstagingdirectory)'

- task: CopyFilesOverSSH@0
  inputs:
    sshEndpoint: 'OVH'
    sourceFolder: '$(build.artifactstagingdirectory)'
    contents: '/'
    targetFolder: '/root/desktop/Rene/Angular/'
    cleanTargetFolder: true

- task: SSH@0
  inputs:
    sshEndpoint: 'OVH'
    runOptions: 'commands'
    commands: 'screen -S frontendrene -p 0 -X stuff "^C^M"; 
      screen -S frontendrene -X stuff "npm install^M";
      screen -S frontendrene -X stuff "ng serve --host 51.77.195.120^M";'